{
 "title": "Airflow Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "num_of_dags",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(airflow_num_of_dags_with_fts, \"metric\", \"with_fts\", \"__name__\", \".*\")\nor\nlabel_replace(airflow_num_of_dags_without_fts, \"metric\", \"fts_disabled\", \"__name__\", \".*\")"
    }
   ]
  },
  {
   "title": "total_queued_tis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(airflow_total_queued_tis_with_fts, \"metric\", \"with_fts\", \"__name__\", \".*\")\nor\nlabel_replace(airflow_total_queued_tis_without_fts, \"metric\", \"fts_disabled\", \"__name__\", \".*\")"
    }
   ]
  },
  {
   "title": "current_queued_tis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(airflow_current_queued_tis_with_fts, \"metric\", \"with_fts\", \"__name__\", \".*\")\nor\nlabel_replace(airflow_current_queued_tis_without_fts, \"metric\", \"fts_disabled\", \"__name__\", \".*\")"
    }
   ]
  },
  {
   "title": "Airflow Running and Queued Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "Airflow Queued Tasks" },
    { "expr": "airflow_executor_running_tasks", "legendFormat": "Airflow Running Tasks" }
   ]
  },
  {
   "title": "task_instances_to_examine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(airflow_task_instances_to_examine_with_fts, \"metric\", \"with_fts\", \"__name__\", \".*\")\nor\nlabel_replace(airflow_task_instances_to_examine_without_fts, \"metric\", \"fts_disabled\", \"__name__\", \".*\")"
    }
   ]
  },
  {
   "title": "total_scheduler_iterations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(airflow_total_scheduler_iterations_with_fts, \"metric\", \"with_fts\", \"__name__\", \".*\")\nor\nlabel_replace(airflow_total_scheduler_iterations_without_fts, \"metric\", \"fts_disabled\", \"__name__\", \".*\")"
    }
   ]
  }
 ]
}