# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
version: "3.8"

# Common
x-redis-env: &redis-env
  ALLOW_EMPTY_PASSWORD: "yes"

x-redis-primary: &redis-primary
  image: bitnami/redis:7.2
  environment:
    <<: *redis-env
  volumes:
    - redis-db-volume:/data/redis
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 5s
    timeout: 30s
    retries: 50
  restart: "on-failure"

x-redis-replica: &redis-replica
  image: bitnami/redis:7.2
  environment:
    <<: *redis-env
    REDIS_MASTER_HOST: redis-primary
    REDIS_MASTER_PORT_NUMBER: 6379
  depends_on: [redis-primary]

x-sentinel: &sentinel-common
  image: bitnami/redis-sentinel:7.2
  environment:
    <<: *redis-env
    REDIS_MASTER_SET: test-cluster
    REDIS_MASTER_HOST: redis-primary
    REDIS_MASTER_PORT_NUMBER: 6379
    REDIS_SENTINEL_QUORUM: 2          # 3 sentinels → quorum of 2
  depends_on:
    - redis-primary
    - redis-replica-1
    - redis-replica-2

# Services
services:
  redis-primary:
    <<: *redis-primary

  redis-replica-1:
    <<: *redis-replica

  redis-replica-2:
    <<: *redis-replica

  sentinel-1:
    <<: *sentinel-common
    hostname: sentinel-1
    # Expose one Sentinel for clients.
    ports: ["26379:26379"]

  sentinel-2:
    <<: *sentinel-common
    hostname: sentinel-2

  sentinel-3:
    <<: *sentinel-common
    hostname: sentinel-3

  airflow:
    depends_on:
      sentinel-1:
        condition: service_started
    environment:
      - INTEGRATION_REDIS_HA=true
      - AIRFLOW__CELERY__BROKER_URL=sentinel://sentinel-1:26379;sentinel://sentinel-2:26379;sentinel://sentinel-3:26379/0
      - AIRFLOW__CELERY__BROKER_TRANSPORT_OPTIONS={"master_name":"test-cluster"}

volumes:
  redis-db-volume:
