# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# NOTE! THIS FILE IS AUTOMATICALLY GENERATED AND WILL BE OVERWRITTEN!
#
# IF YOU WANT TO MODIFY THIS FILE, YOU SHOULD MODIFY THE TEMPLATE
# `get_provider_info_TEMPLATE.py.jinja2` IN the `dev/breeze/src/airflow_breeze/templates` DIRECTORY


def get_provider_info():
    return {
        "package-name": "apache-airflow-providers-apache-kafka",
        "name": "Apache Kafka",
        "description": "`Apache Kafka  <https://kafka.apache.org/>`__\n",
        "integrations": [
            {
                "integration-name": "Apache Kafka",
                "external-doc-url": "https://kafka.apache.org/",
                "how-to-guide": ["/docs/apache-airflow-providers-apache-kafka/sensors.rst"],
                "logo": "/docs/integration-logos/kafka.svg",
                "tags": ["apache"],
            }
        ],
        "operators": [
            {
                "integration-name": "Apache Kafka",
                "python-modules": [
                    "airflow.providers.apache.kafka.operators.consume",
                    "airflow.providers.apache.kafka.operators.produce",
                ],
            }
        ],
        "hooks": [
            {
                "integration-name": "Apache Kafka",
                "python-modules": [
                    "airflow.providers.apache.kafka.hooks.base",
                    "airflow.providers.apache.kafka.hooks.client",
                    "airflow.providers.apache.kafka.hooks.consume",
                    "airflow.providers.apache.kafka.hooks.produce",
                ],
            }
        ],
        "sensors": [
            {
                "integration-name": "Apache Kafka",
                "python-modules": ["airflow.providers.apache.kafka.sensors.kafka"],
            }
        ],
        "triggers": [
            {
                "integration-name": "Apache Kafka",
                "python-modules": [
                    "airflow.providers.apache.kafka.triggers.await_message",
                    "airflow.providers.apache.kafka.triggers.msg_queue",
                ],
            }
        ],
        "connection-types": [
            {
                "hook-class-name": "airflow.providers.apache.kafka.hooks.base.KafkaBaseHook",
                "hook-name": "Apache Kafka",
                "connection-type": "kafka",
                "ui-field-behaviour": {
                    "hidden-fields": ["schema", "login", "password", "port", "host"],
                    "relabeling": {"extra": "Config Dict"},
                    "placeholders": {
                        "extra": '{"bootstrap.servers": "localhost:9092", "group.id": "my-group"}'
                    },
                },
            }
        ],
        "queues": ["airflow.providers.apache.kafka.queues.kafka.KafkaMessageQueueProvider"],
        "plugins": [
            {
                "name": "kafka_listener",
                "plugin-class": "airflow.providers.apache.kafka.plugins.listener.KafkaListenerPlugin",
            }
        ],
        "config": {
            "kafka_listener": {
                "description": "Settings for the Kafka listener that publishes Airflow DagRun and\nTaskInstance state-change events to a Kafka topic.\n",
                "options": {
                    "enabled": {
                        "description": "Enable the Kafka listener. When False the plugin\nregisters no listeners and does no broker work.\n",
                        "version_added": None,
                        "type": "boolean",
                        "example": None,
                        "default": "False",
                    },
                    "bootstrap_servers": {
                        "description": "Comma-separated list of ``host:port`` Kafka bootstrap servers\n(e.g. ``broker1:9092,broker2:9092``). Required to activate\nthe listener — when unset, the plugin registers no hooks\nregardless of ``enabled``. The value is passed straight to\nlibrdkafka as ``bootstrap.servers``.\n",
                        "version_added": None,
                        "type": "string",
                        "example": "broker:29092",
                        "default": "",
                    },
                    "topic": {
                        "description": "Topic the listener publishes events to. The topic must already\nexist on the broker; the listener will not auto-create it.\n",
                        "version_added": None,
                        "type": "string",
                        "example": None,
                        "default": "airflow.events",
                    },
                    "source": {
                        "description": "Identifier added to every emitted message under the ``source``\nfield so consumers can distinguish Airflow installations that\nshare the same topic. When unset, falls back to the hostname\nof the Airflow component that emits the event (scheduler,\nworker, etc.).\n",
                        "version_added": None,
                        "type": "string",
                        "example": "af-prod-eu",
                        "default": "",
                    },
                    "dag_id_allowlist": {
                        "description": "Comma-separated glob patterns. When set, events are only emitted\nfor dag_ids matching at least one pattern. Empty = all dags.\n",
                        "version_added": None,
                        "type": "string",
                        "example": "etl_*,sales_pipeline",
                        "default": "",
                    },
                    "dag_id_denylist": {
                        "description": "Comma-separated glob patterns. dag_ids matching any pattern are\nskipped. Both allowlist and denylist are checked but if a dag_id\nis in both, deny takes precedence.\n",
                        "version_added": None,
                        "type": "string",
                        "example": "tmp_*",
                        "default": "",
                    },
                    "topic_check_timeout": {
                        "description": "How long (in seconds) each topic existence check is allowed\nto block waiting for a response from the broker.\n",
                        "version_added": None,
                        "type": "integer",
                        "example": None,
                        "default": "10",
                    },
                    "topic_check_retry_interval": {
                        "description": "How long (in seconds) to wait before retrying a topic check,\nin case it failed.\n",
                        "version_added": None,
                        "type": "integer",
                        "example": None,
                        "default": "60",
                    },
                },
            }
        },
    }
