# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""
Dags for the UX demo environment.

History for these Dags is generated by ``dev/ux_demo/seed_demo_data.py``; the dag_ids here
must match the seed plans there. See ``dev/ux_demo/README.md``.
"""

from __future__ import annotations

import hashlib
import time
from typing import NamedTuple

import pendulum

from airflow.sdk import DAG, CronTriggerTimetable, get_current_context, task

# Keep in sync with the task duration range in seed_demo_data.py so that live runs
# and seeded runs look alike in the duration charts.
MIN_TASK_SECONDS = 2
MAX_TASK_SECONDS = 8


class DemoDag(NamedTuple):
    dag_id: str
    cron: str | None
    description: str
    owner: str
    tags: list[str]
    # Every task in a stage depends on every task in the previous stage.
    stages: list[list[str]]
    failure_permille: int = 0
    min_task_seconds: int = MIN_TASK_SECONDS
    max_task_seconds: int = MAX_TASK_SECONDS


DEMO_DAGS = [
    DemoDag(
        dag_id="ux_demo_hourly_etl",
        cron="0 * * * *",
        description="Hourly load of orders and customers into the warehouse.",
        owner="data-eng",
        tags=["ux-demo", "etl"],
        stages=[["extract"], ["transform_orders", "transform_customers"], ["load"], ["publish"]],
        failure_permille=5,
    ),
    DemoDag(
        dag_id="ux_demo_frequent_sync",
        cron="*/10 * * * *",
        description="Syncs inventory levels from the shop backend every 10 minutes.",
        owner="platform",
        tags=["ux-demo", "sync"],
        stages=[["poll"], ["sync"], ["verify"]],
        failure_permille=8,
    ),
    DemoDag(
        dag_id="ux_demo_daily_report",
        cron="0 6 * * *",
        description="Builds and sends the daily business report.",
        owner="analytics",
        tags=["ux-demo", "reporting"],
        stages=[
            ["collect"],
            ["aggregate_sales", "aggregate_traffic", "aggregate_costs"],
            ["build_report"],
            ["send_report"],
        ],
        failure_permille=10,
    ),
    DemoDag(
        dag_id="ux_demo_weekday_export",
        cron="0 9 * * 1-5",
        description="Exports the partner feed on working days.",
        owner="partnerships",
        tags=["ux-demo", "export"],
        stages=[["export"], ["upload"]],
        failure_permille=15,
    ),
    DemoDag(
        dag_id="ux_demo_monthly_billing",
        cron="0 0 1 * *",
        description="Monthly invoicing run.",
        owner="finance",
        tags=["ux-demo", "billing"],
        stages=[["gather"], ["invoice"], ["reconcile"], ["archive"]],
        failure_permille=20,
    ),
    DemoDag(
        dag_id="ux_demo_adhoc_reprocess",
        cron=None,
        description="Manually triggered reprocessing. Trigger it to watch a run go through its states.",
        owner="data-eng",
        tags=["ux-demo", "manual"],
        stages=[["prepare"], ["reprocess"], ["validate"]],
        failure_permille=30,
        min_task_seconds=10,
        max_task_seconds=25,
    ),
    DemoDag(
        dag_id="ux_demo_state_showcase",
        cron="*/15 * * * *",
        description="Paused test card: hand-crafted mix of run states, including frozen running/queued runs.",
        owner="ux",
        tags=["ux-demo", "showcase"],
        stages=[["step_1"], ["step_2"], ["step_3"]],
    ),
    DemoDag(
        dag_id="ux_demo_new_pipeline",
        cron="0 12 * * *",
        description="Paused Dag that has never run (empty state).",
        owner="data-eng",
        tags=["ux-demo", "empty"],
        stages=[["start"], ["finish"]],
    ),
]


@task
def simulate_work(min_seconds: int, max_seconds: int, failure_permille: int) -> None:
    """Sleep for a while and fail for a stable, pseudo-random subset of task instances."""
    ti = get_current_context()["ti"]
    digest = hashlib.sha256(f"{ti.dag_id}|{ti.task_id}|{ti.run_id}".encode()).digest()
    sleep_roll = int.from_bytes(digest[:4], "big") % 1000
    failure_roll = int.from_bytes(digest[4:8], "big") % 1000
    time.sleep(min_seconds + (max_seconds - min_seconds) * sleep_roll / 1000)
    if failure_roll < failure_permille:
        raise RuntimeError("Simulated failure for the UX demo")


for demo in DEMO_DAGS:
    with DAG(
        dag_id=demo.dag_id,
        schedule=CronTriggerTimetable(demo.cron, timezone="UTC") if demo.cron else None,
        start_date=pendulum.datetime(2022, 1, 1, tz="UTC"),
        catchup=False,
        max_active_runs=3,
        description=demo.description,
        tags=demo.tags,
        default_args={"owner": demo.owner, "retries": 0},
    ):
        previous_stage: list = []
        for stage in demo.stages:
            current_stage = [
                simulate_work.override(task_id=task_id)(
                    demo.min_task_seconds, demo.max_task_seconds, demo.failure_permille
                )
                for task_id in stage
            ]
            for upstream in previous_stage:
                for downstream in current_stage:
                    upstream >> downstream
            previous_stage = current_stage
